# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df4c9ce3812fa40cec77649b79100814"
name = "Rootly Cart Drawer Upsell"
application_url = "https://homepage-producing-nec-teacher.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/carts/create"
  topics = [ "carts/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/carts/update"
  topics = [ "carts/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/subscriptions/update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]



[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_metaobjects,read_orders,read_products,read_script_tags,write_app_proxy,write_customers,write_metaobject_definitions,write_metaobjects,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://homepage-producing-nec-teacher.trycloudflare.com/api/auth"
]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
